# Generated by Django 5.0.1 on 2024-02-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_category_category_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert')], default='Breakfast', max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
